export const moods = [
  { emoji: "😊", label: "Happy" },
  { emoji: "😢", label: "Sad" },
  { emoji: "😡", label: "Angry" },
  { emoji: "😨", label: "Anxious" },
  { emoji: "😴", label: "Tired" },
  { emoji: "🤕", label: "Dizzy" },
  { emoji: "😐", label: "Neutral" },
];

export const symptoms = [
  "Anxious",
  "Stressed",
  "Fatigued",
  "Dizzy",
  "Headache",
  "Happy",
  "Energetic",
  "Focused",
  "Calm",
  "Bloated",
  "PMS",
  "Pregnancy",
  "Irritable",
  "Insomnia",
  "Brain Fog",
];

export const supplements = [
  // For Anxiety/Stress
  {
    id: "1",
    name: "Magnesium Glycinate",
    description:
      "Highly bioavailable form of magnesium that promotes relaxation",
    benefits: [
      "Reduces anxiety",
      "Improves sleep quality",
      "Muscle relaxation",
    ],
    recommendedFor: ["Anxious", "Stressed", "Insomnia", "Irritable"],
    dosage: "200-400mg before bed",
    type: "Mineral",
    foodSources: [
      "Spinach",
      "Pumpkin seeds",
      "Almonds",
      "Black beans",
      "Avocados",
      "Dark chocolate",
    ],
  },
  {
    id: "2",
    name: "L-Theanine",
    description: "Amino acid found in green tea that promotes calm focus",
    benefits: ["Reduces stress", "Improves focus", "Non-drowsy relaxation"],
    recommendedFor: ["Anxious", "Stressed", "Focused"],
    dosage: "100-400mg daily",
    type: "Amino Acid",
    foodSources: [
      "Green tea",
      "Black tea",
      "Matcha",
      "Certain mushrooms (Bay bolete)",
    ],
  },
  {
    id: "3",
    name: "Ashwagandha",
    description: "Adaptogenic herb that helps the body manage stress",
    benefits: ["Lowers cortisol", "Reduces anxiety", "Improves energy"],
    recommendedFor: ["Anxious", "Stressed", "Fatigued"],
    dosage: "300-600mg daily",
    type: "Herb",
    foodSources: [
      "Ashwagandha root (typically consumed as powder or supplement)",
      "Some herbal teas contain ashwagandha",
    ],
  },

  // For Depression/Mood
  {
    id: "4",
    name: "Vitamin D3 + K2",
    description: "Essential vitamins for mood regulation and bone health",
    benefits: ["Improves mood", "Supports immunity", "Bone health"],
    recommendedFor: ["Sad", "Depressed", "Fatigued"],
    dosage: "1000-5000 IU D3 with 100-200mcg K2",
    type: "Vitamin",
    foodSources: [
      "Fatty fish (salmon, mackerel)",
      "Egg yolks",
      "Fortified dairy products",
      "Mushrooms exposed to sunlight",
      "K2: Natto, fermented foods, cheese",
    ],
  },
  {
    id: "5",
    name: "Omega-3 (EPA/DHA)",
    description: "Essential fatty acids critical for brain health",
    benefits: [
      "Reduces inflammation",
      "Supports brain function",
      "Mood regulation",
    ],
    recommendedFor: ["Sad", "Depressed", "Brain Fog"],
    dosage: "1000-2000mg EPA/DHA daily",
    type: "Fatty Acid",
    foodSources: [
      "Fatty fish (salmon, sardines)",
      "Flaxseeds",
      "Chia seeds",
      "Walnuts",
      "Algal oil (vegan source)",
    ],
  },
  {
    id: "6",
    name: "Saffron Extract",
    description: "Potent herb with mood-boosting properties",
    benefits: [
      "Natural antidepressant",
      "Reduces PMS symptoms",
      "May improve libido",
    ],
    recommendedFor: ["Sad", "Depressed", "PMS"],
    dosage: "30mg daily",
    type: "Herb",
    foodSources: [
      "Saffron spice (expensive)",
      "Some herbal teas",
      "Traditional Persian dishes",
    ],
  },

  // For Energy/Fatigue
  {
    id: "7",
    name: "Rhodiola Rosea",
    description: "Adaptogen that helps combat fatigue and improve endurance",
    benefits: [
      "Reduces fatigue",
      "Improves mental performance",
      "Stress adaptation",
    ],
    recommendedFor: ["Fatigued", "Tired", "Brain Fog"],
    dosage: "200-400mg daily",
    type: "Herb",
    foodSources: [
      "Rhodiola root (typically consumed as supplement or tea)",
      "Some adaptogenic herbal blends",
    ],
  },
  {
    id: "8",
    name: "Coenzyme Q10",
    description: "Antioxidant that supports cellular energy production",
    benefits: [
      "Boosts energy",
      "Supports heart health",
      "Antioxidant protection",
    ],
    recommendedFor: ["Fatigued", "Tired"],
    dosage: "100-300mg daily",
    type: "Antioxidant",
    foodSources: [
      "Organ meats (heart, liver)",
      "Fatty fish",
      "Soybeans",
      "Nuts and seeds",
      "Vegetable oils",
    ],
  },
  {
    id: "9",
    name: "B-Complex",
    description: "Essential vitamins for energy metabolism",
    benefits: [
      "Energy production",
      "Nervous system support",
      "Stress management",
    ],
    recommendedFor: ["Fatigued", "Tired", "Stressed"],
    dosage: "1 capsule daily with food",
    type: "Vitamin",
    foodSources: [
      "Whole grains",
      "Eggs",
      "Meat",
      "Leafy greens",
      "Legumes",
      "Nutritional yeast",
    ],
  },

  // For Focus/Cognition
  {
    id: "10",
    name: "Bacopa Monnieri",
    description: "Traditional herb for memory and cognitive function",
    benefits: ["Improves memory", "Reduces anxiety", "Neuroprotective"],
    recommendedFor: ["Focused", "Brain Fog"],
    dosage: "300mg daily",
    type: "Herb",
    foodSources: [
      "Bacopa herb (typically consumed as supplement or tea)",
      "Some Ayurvedic preparations",
    ],
  },
  {
    id: "11",
    name: "Lion's Mane Mushroom",
    description: "Fungal supplement that supports nerve growth factor",
    benefits: [
      "Cognitive enhancement",
      "Nerve regeneration",
      "May reduce anxiety",
    ],
    recommendedFor: ["Focused", "Brain Fog"],
    dosage: "500-1000mg daily",
    type: "Mushroom",
    foodSources: [
      "Lion's Mane mushroom (can be cooked like other mushrooms)",
      "Powdered supplements",
      "Some mushroom coffees",
    ],
  },

  // For PMS/Pregnancy
  {
    id: "12",
    name: "Evening Primrose Oil",
    description: "Source of GLA, important for hormonal balance",
    benefits: [
      "Reduces PMS symptoms",
      "Supports skin health",
      "May reduce breast pain",
    ],
    recommendedFor: ["PMS", "Bloated"],
    dosage: "1000-2000mg daily",
    type: "Oil",
    foodSources: [
      "Evening primrose seeds (rarely eaten directly)",
      "Typically taken as oil supplement",
    ],
  },
  {
    id: "13",
    name: "Prenatal Multi",
    description: "Comprehensive vitamin/mineral formula for pregnancy",
    benefits: ["Fetal development", "Maternal health", "Energy support"],
    recommendedFor: ["Pregnancy", "Fatigued"],
    dosage: "As directed",
    type: "Multivitamin",
    foodSources: [
      "Leafy greens",
      "Lean meats",
      "Eggs",
      "Dairy",
      "Whole grains",
      "Legumes",
    ],
  },
  {
    id: "14",
    name: "Folic Acid",
    description:
      "Essential B-vitamin that supports fetal neural development during pregnancy",
    benefits: [
      "Prevents neural tube defects",
      "Supports DNA synthesis",
      "Promotes red blood cell formation",
    ],
    recommendedFor: ["Pregnancy"],
    dosage: "400-800 mcg daily or as directed by a healthcare provider",
    type: "Vitamin B9",
    foodSources: [
      "Leafy green vegetables",
      "Citrus fruits",
      "Beans and legumes",
      "Fortified cereals",
      "Beets",
      "Broccoli",
    ],
  },

  // For Headache/Dizziness
  {
    id: "15",
    name: "Feverfew",
    description: "Traditional herb for migraine prevention",
    benefits: ["May reduce migraine frequency", "Anti-inflammatory"],
    recommendedFor: ["Headache", "Dizzy"],
    dosage: "100-300mg daily",
    type: "Herb",
    foodSources: [
      "Feverfew leaves (can be used in teas)",
      "Some herbal supplements",
    ],
  },
  {
    id: "16",
    name: "Ginger Root",
    description: "Natural remedy for nausea and dizziness",
    benefits: [
      "Reduces nausea",
      "Anti-inflammatory",
      "May help with dizziness",
    ],
    recommendedFor: ["Dizzy", "Bloated"],
    dosage: "500-1000mg as needed",
    type: "Herb",
    foodSources: [
      "Fresh ginger root",
      "Ginger tea",
      "Powdered ginger",
      "In many Asian dishes",
    ],
  },

  // For General Well-being
  {
    id: "17",
    name: "Probiotics",
    description: "Beneficial bacteria for gut health",
    benefits: ["Digestive support", "Immune function", "May improve mood"],
    recommendedFor: ["Bloated", "Happy", "Calm"],
    dosage: "10-50 billion CFUs daily",
    type: "Probiotic",
    foodSources: [
      "Yogurt",
      "Kefir",
      "Sauerkraut",
      "Kimchi",
      "Kombucha",
      "Miso",
      "Tempeh",
    ],
  },
  {
    id: "18",
    name: "Zinc",
    description: "Essential mineral for immune function and mood",
    benefits: [
      "Immune support",
      "Hormone regulation",
      "May reduce irritability",
    ],
    recommendedFor: ["Irritable", "PMS"],
    dosage: "15-30mg daily",
    type: "Mineral",
    foodSources: [
      "Oysters",
      "Beef",
      "Pumpkin seeds",
      "Lentils",
      "Chickpeas",
      "Cashews",
    ],
  },
];
