import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  background: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.59)",
  },
  startContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
  },
  title: {
    fontSize: 50,
    fontWeight: "bold",
    color: "teal",
    marginBottom: 10,
    letterSpacing: 1,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    color: "black",
    marginBottom: 40,
    textAlign: "center",
  },
  startButton: {
    backgroundColor: "#7354BF",
    paddingVertical: 15,
    paddingHorizontal: 50,
    borderRadius: 30,
    marginBottom: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  startButtonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  disclaimer: {
    fontSize: 15,
    color: "black",
    textAlign: "center",
    marginTop: 20,
  },
  quizCard: {
    backgroundColor: "#F6F3FF",
    padding: 23,
    borderRadius: 16,
    width: "90%",
    marginHorizontal: "5%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    marginTop: 275,
    alignContent: "center",
  },
  progressContainer: {
    marginBottom: 20,
  },
  progressText: {
    fontSize: 14,
    color: "#7f8c8d",
    marginBottom: 5,
    alignSelf: "flex-end",
  },
  progressBar: {
    height: 3,
    backgroundColor: "white",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#7354BF",
  },
  questionText: {
    fontSize: 22,
    fontWeight: "600",
    marginBottom: 30,
    color: "#2c3e50",
    lineHeight: 30,
    textAlign: "center",
  },
  optionsContainer: {
    marginTop: 10,
  },
  optionButton: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#220A5E",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  optionText: {
    fontSize: 16,
    color: "black",
    textAlign: "center",
  },
  resultContainer: {
    alignItems: "center",
    padding: 20,
    paddingTop: 40,
  },
  resultTitle: {
    fontSize: 23,
    fontWeight: "bold",
    marginBottom: 15,
    color: "black",
    marginTop: 70,
  },
  supplementCard: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 12,
    marginBottom: 15,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  supplementName: {
    fontSize: 20,
    fontWeight: "600",
    color: "#7354BF",
    marginBottom: 8,
  },
  reason: {
    fontSize: 15,
    color: "#34495e",
    lineHeight: 22,
    marginBottom: 10,
  },
  testHeader: {
    fontWeight: "bold",
    marginTop: 10,
    color: "teal",
  },
  testItem: {
    color: "#555",
    marginLeft: 10,
    marginTop: 5,
  },
  restartButton: {
    backgroundColor: "#7354BF",
    padding: 15,
    borderRadius: 30,
    marginTop: 30,
    marginBottom: 20,
    width: "100%",
  },
  restartText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
});

export default styles;
