const Profile = [
  {
    username: "aaliyah123",
    UserFirstname: "Aaliyah",
    UserLastname: "Ali",
    UserEmail: "aaliyah.Ali@gmail.com",
    UserSupplementPreferences: ["Vitamin D", "Magnesium"],
    password: "password1",
  },
  {
    username: "zara456",
    UserFirstname: "Zara",
    UserLastname: "Ahmed",
    UserEmail: "zara.ahmed@hotmail.com",
    UserSupplementPreferences: ["Vitamin C", "Omega-3"],
    password: "password2",
  },
  {
    username: "omar789",
    UserFirstname: "Omar",
    UserLastname: "Siddiqui",
    UserEmail: "omar.siddiqui@gmail.com",
    UserSupplementPreferences: ["Multivitamin", "Probiotics"],
    password: "password3",
  },
  {
    username: "nadia101",
    UserFirstname: "Nadia",
    UserLastname: "Raza",
    UserEmail: "nadia.raza@yahoo.com",
    UserSupplementPreferences: ["Vitamin B12", "Iron"],
    password: "password4",
  },
  {
    username: "bilal202",
    UserFirstname: "Bilal",
    UserLastname: "Farooq",
    UserEmail: "bilal.farooq@gmail.com",
    UserSupplementPreferences: ["Zinc", "Vitamin E"],
    password: "password5",
  },
  {
    username: "ali303",
    UserFirstname: "Ali",
    UserLastname: "Wali",
    UserEmail: "ali.wali@yahoo.com",
    UserSupplementPreferences: ["Calcium", "Vitamin D"],
    password: "password6",
  },
  {
    username: "sara404",
    UserFirstname: "Sara",
    UserLastname: "Rehman",
    UserEmail: "sara.rehman@hotmail.com",
    UserSupplementPreferences: ["Biotin", "Magnesium"],
    password: "password7",
  },
  {
    username: "ahmed505",
    UserFirstname: "Ahmed",
    UserLastname: "Shah",
    UserEmail: "ahmed.shah@gmail.com",
    UserSupplementPreferences: ["Vitamin A", "Omega-3"],
    password: "password8",
  },
];
export default Profile;
